spring:
  config:
    activate:
      on-profile: prod

  jpa:
    properties:
      hibernate:
        ddl_auto: update  # 운영서버에서 원래는 validate 또는 none 으로 설정해야함
        format_sql: true
        show_sql: true

  data:
    redis:
      port: 6379
      host: 10.176.8.126
      connect-timeout: 1000

  datasource:
    master:
      hikari:
        jdbc-url: jdbc:mysql://10.240.80.11:3306/moa_meeting
        read-only: false
        username: root
        password: ${MASTER_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      hikari:
        jdbc-url: jdbc:mysql://10.240.80.13:3306/moa_meeting
        read-only: true
        username: root
        password: ${SLAVE_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

  # Kafka 설정 추가
  kafka:
    bootstrap-servers: 10.176.12.164:9092 # Kafka 서비스의 CLUSTER-IP와 포트 -> 나중에 적용
#    bootstrap-servers: 34.64.189.14:9092 # Kafka 서비스의 EXTERNAL-IP와 포트
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: my-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  # elastic search 설정 추가
#  elasticsearch:
#    rest.uris: https://10.176.14.192:9200
#    rest.username: awdfaf
#    rest.password: awdfaf

logging.level: # 서버 디버깅용 임시 설정
  org.hibernate.orm.jdbc.bind: trace
  com.moa.user: DEBUG
