{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "be-search.serviceAccountName" . }}
  labels:
    {{- include "be-search.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  # automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
